Remove 'uReconstruct{Zonal,Meridional}' fields from atmosphere restart stream
MPAS-Dev/MPAS-Model pull request #1016
Opened 2022-12-28 23:56 UTC by mgduda

This PR removes the `uReconstruct{Zonal,Meridional}` fields from the atmosphere core's
restart stream.

The `uReconstructZonal` and `uReconstructMeridional` fields are always computed when the model starts up and do not need to be written and read from the atmosphere core's restart stream.

2023-01-03 17:09 UTC, gdicker1 requested changes
I can't convince myself that "... fields are always computed when the model starts up" is true so far from looking at the code. I might need some extra guidance either personally or from the PR message.

So far I've looked through most of the initialization execution path and don't see where any uReconstruct variables would have been initialized. Near as I can tell those variables are updated whenever `mpas_reconstruct` is called in [`atm_srk3` near line 1098](https://github.com/MPAS-Dev/MPAS-Model/blob/153aebb1c0171c654a0a7ab76e6751186606c7b5/src/core_atmosphere/dynamics/mpas_atm_time_integration.F#L1098), but I think I'm wrong.

2023-01-05 05:05 UTC, mgduda commented
@gdicker1 I've updated the commit message and PR description to call out where the `uReconstructZonal` and `uReconstructMeridional` fields are computed at model start-up. Does the updated text seem sufficient?

2023-01-07 18:45 UTC, gdicker1 commented
See this comment in PR #1017 for the test I did of this PR.

https://github.com/MPAS-Dev/MPAS-Model/pull/1017#issuecomment-1374571056

2023-01-17 01:14 UTC, gdicker1 approved these changes
Apologies, my last comment was meant to be an approval. Looks good to me!

2023-01-17 17:48 UTC, merged