Enable GPU exection of atm_compute_moist_coefficients via OpenACC
MPAS-Dev/MPAS-Model pull request #1238
Opened 2024-10-17 23:56 UTC by abishekg7

This PR enables the GPU execution of atm_compute_moist_coefficients subroutine.

Tested with a real and idealized test cases.

2025-01-02 21:53 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop
I think the loop directives should be more explicit (e.g. `loop gang worker` here). Just to match with other work we're doing.

2025-01-02 21:53 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc exit data copyout(cqw, cqu, qtot) delete(scalars)
This `exit data` directive should be surrounded by `MPAS_ACC_TIMER_{START,STOP}` calls.

2025-01-02 22:10 UTC, gdicker1 requested changes
This may need some additional work. When I compared baseline and test runs of the regional testcase, I get differences in two fields in the history file. Restart files are reported as matching.

Output from compare_netcdf.py:
```
Comparing files: f1 - f2                                                                                                                             
        f1=../2024Dec31_MPASAPR1223_OpenACC/baseline_acc_1735844488/history.2019-09-01_00.06.00.nc                                                   
        f2=test_att1735694999/history.2019-09-01_00.06.00.nc                                                                                         

            Variable  Min       Max       
=========================================
initial_time is not a numeric field and will not be compared
xtime is not a numeric field and will not be compared
        depv_dt_fric -32.448421  33.315609
     depv_dt_fric_pv -32.448421  30.517973
mminlu is not a numeric field and will not be compared
```

Also a couple of suggested edits.

2025-01-14 16:47 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc exit data copyout(cqw, cqu, qtot) delete(scalars)
As I commented on another PR, I'd also advocate for at least splitting the `copyout` and `delete` clauses onto separate lines, or better yet, to turn them into separate directives. I think this will make it easier when it comes to shifting around and fusing data directives later, and at least for me, it just makes it easier to visually recognize that there are two things happening in this `exit data` directive.

2025-01-14 23:11 UTC, abishekg7 commented
Modified the two parallel constructs to explicitly specify the level of parallelism. This also seems to lead to a performance increase for the limited area test by about 10% in the parallel clause on L1754 and about 51% on L1767. Also verified that results are still bit reproducible.

Added timers around the exit data clause and made the other suggested formatting changes. 

The differences in the diagnostic fields in the history files are expected per our previous discussion.

2025-01-15 02:27 UTC, mgduda requested changes

2025-01-15 02:27 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc enter data copyin(qtot, cqw, cqu, scalars)
If I'm not mistaken, we only need to `create`, rather than `copyin`, the variables `qtot`, `cqw`, and `cqu`.

2025-01-15 23:26 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc enter data copyin(qtot, cqw, cqu, scalars)
The line that you referenced only initializes the garbage cell for `qtot`. Setting aside our recent experience with the garbage cell for `theta_m`, I don't think the specific value in the garbage cell for `qtot` should matter, in which case `create` should be fine in the `!$acc data` directive.

2025-01-15 23:56 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc enter data copyin(qtot, cqw, cqu, scalars)
Got it. I changed it the three variables to `create` now, and the results are still bit identical.

2025-01-16 00:31 UTC, mgduda commented
@abishekg7 The code changes themselves look good to me now. I'd only request that the commit history be cleaned up, and perhaps just a single commit would suffice.

2025-01-16 01:20 UTC, abishekg7 commented
Rebased this PR and ran a quick check for bit reproducibility again. thanks for the review!

2025-01-16 01:25 UTC, mgduda approved these changes

2025-01-16 01:26 UTC, mgduda commented
> Rebased this PR and ran a quick check for bit reproducibility again. thanks for the review!

Nice work!

2025-01-16 03:00 UTC, gdicker1 approved these changes
This looks good to me!

2025-01-16 21:38 UTC, merged