Enable GPU execution of atm_compute_vert_imp_coefs via OpenACC
MPAS-Dev/MPAS-Model pull request #1241
Opened 2024-10-23 22:15 UTC by abishekg7

2024-11-01 20:41 UTC, mgduda commented
@abishekg7 Can you clean up the commits and add a description to this PR?

2024-11-06 22:55 UTC, abishekg7 commented
> @abishekg7 Can you clean up the commits and add a description to this PR?

Thanks. Done!

2025-01-02 22:01 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc                   rtb, rt, pb)
Some of the fields here are invariant (across timesteps) and should be handled in the `mpas_atm_dynamics_{init,finalize}` routines instead.

Generally these invariant fields are those contained in the "invariant stream" ([L421-L524 in the atm Registry.xml](https://github.com/MPAS-Dev/MPAS-Model/blob/41e9a3fb8ca6b9250a7405209a5c60996318409f/src/core_atmosphere/Registry.xml#L421-L524)) or those accessed through the "mesh" `mpas_pool` ([L1222-L1516 in the atm Registry.xml](https://github.com/MPAS-Dev/MPAS-Model/blob/41e9a3fb8ca6b9250a7405209a5c60996318409f/src/core_atmosphere/Registry.xml#L1222-L1516))

2025-01-02 22:02 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop
I think it would be better to be explicit with `loop` directives (e.g. `loop gang worker` here).

2025-01-02 22:04 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc exit data delete(rdzw, zz, fzm, fzp, rdzu, cqw, p, t, qtot, rb, rtb, rt, pb)
Besides handling fields like `fzm` in `mpas_atm_dynamics_finalize` instead, these directives should be surrounded by `MPAS_ACC_TIMER_{START,STOP}` calls.

2025-01-02 22:08 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +
This empty line contains extra spaces that should be removed. Might be good to double check for any trailing whitespace in the lines you're adding.

2025-01-02 22:09 UTC, gdicker1 requested changes
This PR may need a little more work. I'm getting differences in 2 fields in the history file when comparing the regional testcase. Restart files are reported as matching.

Output from compare_netcdf.py:
```
Comparing files: f1 - f2                                                                                                                             
        f1=../2024Dec31_MPASAPR1223_OpenACC/baseline_acc_1735844488/history.2019-09-01_00.06.00.nc                                                   
        f2=test_att1735695005/history.2019-09-01_00.06.00.nc                                                                                         
                                                                                                                                                     
            Variable  Min       Max                                                                                                                  
=========================================
initial_time is not a numeric field and will not be compared
xtime is not a numeric field and will not be compared
        depv_dt_fric -32.448421  33.315609
     depv_dt_fric_pv -32.448421  30.517973
mminlu is not a numeric field and will not be compared
```

Some suggested edits as well.

2025-01-09 17:11 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc                   rtb, rt, pb)
Done. thanks for the catch!

2025-01-09 17:12 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc exit data delete(rdzw, zz, fzm, fzp, rdzu, cqw, p, t, qtot, rb, rtb, rt, pb)
Done.

2025-01-09 17:15 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +
Done. thanks!

2025-01-15 16:03 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc enter data copyin(rdzw)
Caught an issue here. It should be `exit data delete`, not `enter data copyin`

2025-01-15 16:07 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop
Done. No performance penalties for this change, with the limited area case at least.

2025-01-16 00:32 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc parallel
As with other routines, should we add `default(present)` clauses to the `parallel` directives in this routine as well?

2025-01-16 01:15 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc parallel
fixed, and thanks!

2025-01-16 01:17 UTC, mgduda commented
@abishekg7 The code changes themselves look good to me now. I'd only request that the commit history be cleaned up. If you want to keep the handling of the time-invariant fields in a separate commit, that seems fine, but just a single commit for this PR seems sufficient.

2025-01-16 16:31 UTC, abishekg7 commented
Rebased and squashed to a single commit, and results are still bit identical.

2025-01-16 16:49 UTC, gdicker1 commented
@abishekg7, I think everything is looking good except this sentence in the commit message

> - The parallel clauses now specify a default(present)

This seems like an incomplete thought, like there should be more after "...sent)". Maybe as short as:

> - The parallel regions use default(present) clauses.

With something about "to enforce data management" potentially being added too.

Aside: As I understand OpenACC terminology, _directives_ refer to the part of the statement right after `acc`. E.g. "parallel", "kernels", "host_data", "data", and "exit data" . If the directive applies to a region of code, the directive and the region together are a _construct_. _Clauses_ are the other statements that come after the directive (like "collapse(n)" or "async").

2025-01-16 16:55 UTC, abishekg7 commented
> @abishekg7, I think everything is looking good except this sentence in the commit message
> 
> > * The parallel clauses now specify a default(present)
> 
> This seems like an incomplete thought, like there should be more after "...sent)". You could drop the "a" or replace the sentence with something like:
> 
> > * The parallel constructs use default(present) clauses.
> 
> With something about "to enforce data management" potentially being added too.
> 
> Aside: As I understand OpenACC terminology, _directives_ refer to the part of the statement right after `acc`. E.g. "parallel", "kernels", "host_data", "data", and "exit data" . If the directive applies to a region of code, the directive and the region together are a _construct_. _Clauses_ are the other parts of a statement that come after the directive (like "collapse(n)" or "async").

Thanks @gdicker1! I've been using clauses, directives and constructs interchangeably and it's good to know. Will fix this.

2025-01-16 17:33 UTC, abishekg7 commented
Fixed the default(present) part of the commit message.

2025-01-16 17:47 UTC, gdicker1 approved these changes
Looks good to me now!

2025-01-17 00:58 UTC, mgduda approved these changes
Looks good to me!

2025-01-17 01:03 UTC, merged