Enable GPU exection of atm_advance_acoustic_step via OpenACC
MPAS-Dev/MPAS-Model pull request #1251
Opened 2024-12-06 02:11 UTC by gdicker1

This PR makes small code modifications and adds OpenACC directives so the `atm_advance_acoustic_step_work` routine can execute on GPU(s).

Timing information for the OpenACC data transfers in this routine is captured in the log file by a new timer: `atm_advance_acoustic_step [ACC_data_xfer]`.

Invariant fields used in this routine are also copied to the device within `mpas_atm_dynamics_init` and are deleted in `mpas_atm_dynamics_finalize`.

2024-12-16 18:00 UTC, gdicker1 commented
NOTE: This PR is paused. I am sorting out the merge conflicts and a run-time error. I will notify again when this PR is ready for review.

2025-01-07 20:55 UTC, gdicker1 commented
Force push from [58ba84a](https://github.com/MPAS-Dev/MPAS-Model/commit/58ba84a54822d39b7a6a641926578396768a128d) to [0730fa2](https://github.com/MPAS-Dev/MPAS-Model/commit/0730fa2c27290c3cf5951444852902e1cf3df46d) is to bring this more in line with the develop branch. This PR should now be ready for review, @mgduda!

2025-01-10 19:39 UTC, gdicker1 commented
Force-push [0730fa2](https://github.com/MPAS-Dev/MPAS-Model/commit/0730fa2c27290c3cf5951444852902e1cf3df46d) to [09e60a5](https://github.com/MPAS-Dev/MPAS-Model/commit/09e60a5c32d0723cdc1e422d8c9d76ecf5f6dea0) to consistently add new invariant fields at the end of sections in `mpas_atm_dynamics_{init,finalize}`.

@mgduda and @abishekg7 this should be ready for review!

2025-01-16 00:39 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +        !$acc parallel
Should we add `default(present)` here?

2025-01-16 17:04 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
>              end do
Question for @mgduda and @gdicker1 : We could perhaps rewrite this loop with an `acc reduction(+: flux.. etc)` instead of `acc loop seq`, but would our priority right now be to reorder the code as little as possible? I also have similar loops in the PR I'm working on. 

(I did quickly try using reduction for this loop, but it didn't really result in any performance improvement. But perhaps there might be something off in my code)

2025-01-16 17:15 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
>              end do
I think there's value in trying to modify the code as little as possible during this phase of the porting work.

2025-01-16 17:16 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop gang private(ts,rs)
I was wondering the same.

2025-01-16 17:38 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop gang private(ts,rs)
I think `worker` wasn't specified in case I needed that level in this big loop. I can add it easily

2025-01-16 18:52 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
>              end do
I agree with both points - `ts` and `rs` seems like good candidates for a reduction clause here and we also shouldn't re-write the loop (yet). I'll keep this in mind for our optimization phase.

2025-01-16 19:00 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
>              end do
Yeah, that makes sense. I'll also follow a similar approach for now with my PRs.

2025-01-17 17:03 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +        !$acc parallel
Yes, addressed now by fixup [d7109c1](https://github.com/MPAS-Dev/MPAS-Model/pull/1251/commits/d7109c12aed15227e61242b8c07ac32233b110bd)

2025-01-17 17:04 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop gang private(ts,rs)
Well after "easily" turned out to be harder than I thought, this is now addressed by fixup [2030ecc](https://github.com/MPAS-Dev/MPAS-Model/pull/1251/commits/2030eccb9dd64748426a5fe82d8132fe45f71edf)

2025-01-17 17:06 UTC, gdicker1 commented
@mgduda and @abishekg7 this is ready for review now if you want. I plan to squash this into one commit like #1237 later today if you'd rather review that.

2025-01-17 23:02 UTC, gdicker1 commented
@mgduda and @abishekg7, force-push [2030ecc](https://github.com/MPAS-Dev/MPAS-Model/commit/2030eccb9dd64748426a5fe82d8132fe45f71edf) to [6ec497f](https://github.com/MPAS-Dev/MPAS-Model/commit/6ec497f23b9ec162f228fb2824992cd66fd4dd5a) squashed this to one commit. Let me know what you think!

2025-01-18 00:32 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +>>>>>>> d7109c12a (fixup! Add acc data movement to atm_advance_acoustic_step_work)
There's a merge conflict here fyi.

2025-01-18 00:33 UTC, abishekg7 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop gang private(ts,rs)
Also here

2025-01-21 18:48 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +>>>>>>> d7109c12a (fixup! Add acc data movement to atm_advance_acoustic_step_work)
Thanks for spotting it. I'll get that sorted.

2025-01-21 19:00 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +>>>>>>> d7109c12a (fixup! Add acc data movement to atm_advance_acoustic_step_work)
Addressed by force-push [68253c3](https://github.com/MPAS-Dev/MPAS-Model/commit/68253c37370aecd6e58966569ad217c03d041042) to [6e40864](https://github.com/MPAS-Dev/MPAS-Model/commit/6e40864b4974f57ce6fbbfe30437cf16c291260c).

2025-01-21 19:00 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +      !$acc loop gang private(ts,rs)
Thanks again. Addressed by force-push [68253c3](https://github.com/MPAS-Dev/MPAS-Model/commit/68253c37370aecd6e58966569ad217c03d041042) to [6e40864](https://github.com/MPAS-Dev/MPAS-Model/commit/6e40864b4974f57ce6fbbfe30437cf16c291260c).

2025-01-21 21:50 UTC, abishekg7 approved these changes
Tested with both limited area and J-W baroclinic cases, and get bit identical results with the develop branch. Looks good.

2025-01-30 23:34 UTC, mgduda requested changes

2025-01-30 23:34 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> -              end do
I would suggest we avoid fusing loops for now in an attempt to keep the ported code as close to the original as possible. Taking this change specifically, it was around a decade ago that we specifically split the computation of `ruAvg` into a separate `k`-loop: see c0dae351. Unfortunately, the commit message for c0dae351 is rather terse, so I can only guess now that the reason was to improve vectorization.

2025-01-30 23:34 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> -              end do
Similarly here, I'd suggest we keep two separate `k`-loops for now.

2025-01-30 23:34 UTC, mgduda commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +         end do
I would suggest we leave this initialization code in the loop further down (around line 2576).

2025-01-30 23:36 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> -              end do
Understood, I'll get that changed.

2025-01-31 01:19 UTC, gdicker1 commented on src/core_atmosphere/dynamics/mpas_atm_time_integration.F
> +         end do
I will do as asked, and keep the modifications to a minimum.

Though, it seems like bad form to have an if condition inside a loop that doesn't depend on variables in the loop - especially when the code block immediately above tests the same condition and has similar behavior.

2025-01-31 01:57 UTC, gdicker1 commented
@mgduda ready for re-review after force-push [6e40864](https://github.com/MPAS-Dev/MPAS-Model/commit/6e40864b4974f57ce6fbbfe30437cf16c291260c) to [c304356](https://github.com/MPAS-Dev/MPAS-Model/commit/c304356eee82d3f9de14fcf1b19dcf864897f640)

2025-01-31 18:02 UTC, mgduda approved these changes

2025-01-31 18:03 UTC, merged