Addition of the new static information: BNU soil types and 15" MODIS landuse
MPAS-Dev/MPAS-Model pull request #1252
Opened 2024-12-12 23:46 UTC by tanyasmirnova

The title above should be a 1 line short summary of the pull request (i.e. what the project the PR represents is intended to do).

Enter a description of this PR. This should include why this PR was created, and what it does.
The BNU soil dataset has the same soil categories as in STATSGO with differences in spatial variations.
The MODIFIED_IGBP_MODIS_NOAH_15s has the same categories as in MODIFIED_IGBP_MODIS_NOAH.
The additional static information is introduced via the namelist.init_atmosphere
    config_landuse_data = 'MODIFIED_IGBP_MODIS_NOAH_15s'
    config_soilcat_data = 'BNU'

Testing and relations to other Pull Requests should be added as subsequent comments.

See the below examples for more information.
https://github.com/MPAS-Dev/MPAS/pull/930
https://github.com/MPAS-Dev/MPAS/pull/931

2025-01-31 22:24 UTC, mgduda requested changes

2025-01-31 22:24 UTC, mgduda commented on src/core_init_atmosphere/Registry.xml
> +	        <nml_option name="config_nsoilcat"              type="integer"       default_value="16"
It doesn't look like `config_nsoilcat` is used anywhere, so it seems like we could remove it from this PR branch.

2025-01-31 22:24 UTC, mgduda commented on src/core_init_atmosphere/mpas_init_atm_static.F
> + call mpas_pool_get_config(configs, 'config_soilcat_data', config_soilcat_data)
It looks like the definition of `config_soilcat_data` is missing from the `Registry.xml` file.

2025-01-31 22:24 UTC, mgduda commented on src/core_init_atmosphere/Registry.xml
> +	        <nml_option name="config_supersample_fac_lu"    type="integer"       default_value="1"
Just as an idea, what if we called this `config_lu_supersample_factor`? That name would match the pattern set by the two existing super-sampling options nicely: `config_supersample_factor`, `config_lu_supersample_factor`, and `config_30s_supersample_factor`.

2025-02-01 19:29 UTC, tanyasmirnova commented on src/core_init_atmosphere/Registry.xml
> +	        <nml_option name="config_supersample_fac_lu"    type="integer"       default_value="1"
Thank you for the idea. The name is changed as you suggested.

2025-02-01 19:32 UTC, tanyasmirnova commented on src/core_init_atmosphere/Registry.xml
> +	        <nml_option name="config_nsoilcat"              type="integer"       default_value="16"
@mgduda Mike, this variable will be used in the following PRs that will compute the fractional content of soil types in each grid cell. And the 3-d array of fractional soil types will be dimensioned as nsoilcat.

2025-02-01 19:40 UTC, tanyasmirnova commented on src/core_init_atmosphere/mpas_init_atm_static.F
> + call mpas_pool_get_config(configs, 'config_soilcat_data', config_soilcat_data)
Mike, sorry about that. I added config_soilcat_data to the Registry.xml

2025-05-14 18:20 UTC, mgduda commented on src/core_init_atmosphere/Registry.xml
> +	        <nml_option name="config_nsoilcat"              type="integer"       default_value="16"
@tanyasmirnova Apologies for the long delay in following up on this PR. If the `config_nsoilcat` option will be used in a future PR, perhaps we could add it to the `Registry.xml` file at that time?

2025-05-14 18:21 UTC, mgduda commented on src/core_init_atmosphere/mpas_init_atm_static.F
> + call mpas_pool_get_config(configs, 'config_soilcat_data', config_soilcat_data)
Thanks!

2025-05-14 18:49 UTC, tanyasmirnova commented on src/core_init_atmosphere/Registry.xml
> +	        <nml_option name="config_nsoilcat"              type="integer"       default_value="16"
@mgduda Michael, yes, we can add config_nsoilcat later.

2025-05-16 22:37 UTC, mgduda commented on src/core_init_atmosphere/mpas_init_atm_static.F
> +    case('STASGO')
Should this be `STATSGO`?

2025-05-16 22:44 UTC, tanyasmirnova commented on src/core_init_atmosphere/mpas_init_atm_static.F
> +    case('STASGO')
@mgduda I saw it is called both ways. But agree we can use STATSGO here.

2025-05-17 02:05 UTC, mgduda commented on src/core_init_atmosphere/mpas_init_atm_static.F
> +       write(mminlu,'(a)') 'MODIFIED_IGBP_MODIS_NOAH_15s'
In case the resolution of the input land use data (30s versus 15s) makes no difference to the model, would it be reasonable to set `mminlu` equal to `MODIFIED_IGBP_MODIS_NOAH` if `config_landuse_data` is either `MODIFIED_IGBP_MODIS_NOAH` or `MODIFIED_IGBP_MODIS_NOAH_15s`? That would remove the need for changes to the logic in `mpas_atmphys_landuse.F`.

2025-05-19 18:17 UTC, tanyasmirnova commented on src/core_init_atmosphere/mpas_init_atm_static.F
> +       write(mminlu,'(a)') 'MODIFIED_IGBP_MODIS_NOAH_15s'
@mgduda agree that mminlu could be set to MODIFIED_IGBP_MODIS_NOAH. Thank you!

2025-05-19 20:34 UTC, mgduda commented
@tanyasmirnova Thanks very much for the replies to comments. I have a revised version of this branch that incorporates some of the changes noted in comments, and I've also reworked the commit history to have just a few commits. If you'd like, I could push this updated branch to your fork, and that would automatically update this PR. However, if you would prefer to incorporate the changes following the comments on this PR yourself, just let me know. Thanks!

2025-05-19 20:39 UTC, tanyasmirnova commented
> @tanyasmirnova Thanks very much for the replies to comments. I have a revised version of this branch that incorporates some of the changes noted in comments, and I've also reworked the commit history to have just a few commits. If you'd like, I could push this updated branch to your fork, and that would automatically update this PR. However, if you would prefer to incorporate the changes following the comments on this PR yourself, just let me know. Thanks!

Michael, thank you very much. I would appreciate if you push the updated branch to my PR. Thank you.

2025-05-20 19:58 UTC, tanyasmirnova commented
Michael,
Thank you for the instructions.
Unfortunately I got this trying to clone the code:
***@***.*** MPAS_code]$ git clone -b MPAS_ncar_static
***@***.***:tanyasmirnova/MPAS-Model.git PR1252
Cloning into 'PR1252'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The RSA host key for github.com has changed,
and the key for the corresponding IP address 140.82.112.3
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /home/Tanya.Smirnova/.ssh/known_hosts to get rid of
this message.
Offending RSA key in /home/Tanya.Smirnova/.ssh/known_hosts:439
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle
attacks.
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I think something has changed in the access rights to NCAR repositories.
Do you know how to fix this?
Thank you,
Tanya


On Mon, May 19, 2025 at 9:08 PM Michael Duda ***@***.***>
wrote:

> *mgduda* left a comment (MPAS-Dev/MPAS-Model#1252)
> <https://github.com/MPAS-Dev/MPAS-Model/pull/1252#issuecomment-2892775548>
>
> Michael, thank you very much. I would appreciate if you push the updated
> branch to my PR. Thank you.
>
> It seems that I don't have permission to push to the MPAS_ncar_static
> branch in your fork. But, I have pushed the reworked branch to my fork (
> mgduda/MPAS_ncar_static
> <https://github.com/mgduda/MPAS-Model/commits/MPAS_ncar_static/>). Could
> you try the following to overwrite the MPAS_ncar_static branch in your
> fork?
>
> git clone -b MPAS_ncar_static ***@***.***:tanyasmirnova/MPAS-Model.git PR1252
> cd PR1252
> git remote add -f mgduda ***@***.***:mgduda/MPAS-Model.git
> git reset --hard mgduda/MPAS_ncar_static
> git push --force origin MPAS_ncar_static
>
> If you run into any issues, just let me know and I'll be glad to help.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MPAS-Dev/MPAS-Model/pull/1252#issuecomment-2892775548>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJHANABLHSH5R3HNGYTNVS327KMCHAVCNFSM6AAAAABTQ35AKKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDQOJSG43TKNJUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-05-20 23:31 UTC, mgduda commented
@tanyasmirnova I think this is the relevant part of the error message:
```
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in /home/Tanya.Smirnova/.ssh/known_hosts to get rid of
this message.
Offending RSA key in /home/Tanya.Smirnova/.ssh/known_hosts:439
```
According to [this documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints), the fingerprint for the RSA key looks safe. I think you could just try deleting the key in your `/home/Tanya.Smirnova/.ssh/known_hosts` file at line 439 (you could make a backup copy of the `known_hosts` file just in case...).

2025-05-21 19:16 UTC, tanyasmirnova commented
Michael,
I removed line 439 in known_hosts.
Now I get this error:
***@***.*** MPAS_code]$ git clone -b MPAS_ncar_static
***@***.***:tanyasmirnova/MPAS-Model.git PR1252
Cloning into 'PR1252'...
Warning: Permanently added 'github.com,140.82.114.4' (ECDSA) to the list of
known hosts.
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Also on 19 May I got the following message from github:
You have been removed from the "NSF National Center for Atmospheric
Research" organization

Hi @tanyasmirnova,

You've been removed as a collaborator on "NSF National Center for
Atmospheric Research"'s repositories because you do not meet the two-factor
authentication requirements of "NSF National Center for Atmospheric
Research". The "NSF National Center for Atmospheric Research" organization
requires all affiliated users to have two-factor authentication enabled.


Review two-factor authentication

What happens after that?

After you've adjusted your two-factor authentication settings to be
compliant with the above, contact a member of your organization to let them
know you want your access restored. Only a person with owner permissions in
your organization can restore your previous privileges directly. If the
person you contact isn't an organization owner, they can look up an
organization owner and forward your request to them.

Trouble with the button above? Copy and paste the following link into your
browser:
https://github.com/settings/security

You no longer have access to the following repositories:

"NCAR/ccpp-scm"
"NCAR/ccpp-framework"
"NCAR/gmtb-fv3"
"NCAR/ccpp-physics"
"NCAR/NEMSfv3gfs"
"NCAR/FV3"
"NCAR/NEMS.depricated"
"climbfuji/NEMSfv3gfs"
"climbfuji/FV3"
"climbfuji/NEMS-Vlab-old"
"NCAR/fv3atm"
"NCAR/ufs-weather-model"

I heard that many people in our group got the same message.
Do you think it could be the reason for the problem with accessing the NCAR
repository?

Thank you,
Tanya



On Tue, May 20, 2025 at 5:31 PM Michael Duda ***@***.***>
wrote:

> *mgduda* left a comment (MPAS-Dev/MPAS-Model#1252)
> <https://github.com/MPAS-Dev/MPAS-Model/pull/1252#issuecomment-2896057751>
>
> @tanyasmirnova <https://github.com/tanyasmirnova> I think this is the
> relevant part of the error message:
>
> The fingerprint for the RSA key sent by the remote host is
> SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
> Please contact your system administrator.
> Add correct host key in /home/Tanya.Smirnova/.ssh/known_hosts to get rid of
> this message.
> Offending RSA key in /home/Tanya.Smirnova/.ssh/known_hosts:439
>
> According to this documentation
> <https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints>,
> the fingerprint for the RSA key looks safe. I think you could just try
> deleting the key in your /home/Tanya.Smirnova/.ssh/known_hosts file at
> line 439 (you could make a backup copy of the known_hosts file just in
> case...).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MPAS-Dev/MPAS-Model/pull/1252#issuecomment-2896057751>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJHANAGKHPX27O5W7YZXVPD27O3OFAVCNFSM6AAAAABTQ35AKKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDQOJWGA2TONZVGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-05-22 23:06 UTC, mgduda commented
This PR has been replaced by #1322.

2025-05-22 23:06 UTC, closed without merging