Added OpenACC directives to Convection and New Tiedtke model, for GPU execution.
MPAS-Dev/MPAS-Model pull request #897
Opened 2021-07-28 15:40 UTC by cponder

Added OpenACC directives from 6.x-openacc version to manage Host <-> GPU memory movement, to enable convection model to run on the GPU.

2021-08-02 22:57 UTC, cponder commented
The second commit was to remove deprecated array names from the Device -> Host update.

2021-08-03 19:33 UTC, supreethms1809 requested changes
Apart from two general comments the openacc port looks good. Will wait for @Pranay-Reddy-Kommera confirmation to start the runs and validation.

2021-08-03 19:33 UTC, supreethms1809 commented on src/core_atmosphere/physics/mpas_atmphys_driver_convection.F
> +
@cponder I think we need to get rid of all these debug messages by submitting one more commit

2021-08-03 19:33 UTC, supreethms1809 commented on src/core_atmosphere/physics/mpas_atmphys_driver_convection.F
> +
There are multiple debug messages below. the above comment applies to all of them

2021-08-03 19:33 UTC, supreethms1809 commented on src/core_atmosphere/physics/physics_wrf/module_cu_ntiedtke.F
> +!!!   do j=jts,jte
@cponder instead of commenting the deleted code in V7. I think we should delete it as well

2021-08-03 22:16 UTC, mgduda commented
Following a discussion with @raghuraj19, I've added the "Don't merge" label: we need to wait until @Pranay-Reddy-Kommera's PRs have been merge before merging this PR.

2021-09-04 21:50 UTC, cponder commented
I've had to re-work the changes to go with #909 & #910.
I wrote a new PR #927 and am closing this one.

2021-09-04 21:50 UTC, closed without merging