Start module names in atmosphere diagnostics with "mpas_"
MPAS-Dev/MPAS-Model pull request #993
Opened 2022-09-30 18:24 UTC by gdicker1

To ensure the functions in atmosphere diagnostics have unique names when compiled, this PR modifies the module names to begin with "mpas_".

Unique function and module names are typically easy to ensure within one project, but the diagnostics are a potential issue when MPAS-A is used as part of a larger model. Some diagnostics may be almost identical and exist in both models. Adding this "mpas_" prefix to the module names will help ensure name conflicts don't occur.

2022-10-07 19:01 UTC, gdicker1 commented
This has been tested on Cheyenne by building and running a [FHS94](https://www.cesm.ucar.edu/models/simpler-models/changedycore.html) compset of CESM using a 480km MPAS grid. Adding these changes to the MPAS code did not cause any issues with the build/run.

2022-10-18 15:43 UTC, mgduda commented
@gdicker1 In the description of the PR, I think we had discussed the possibility that the statement "To ensure the functions in atmosphere diagnostics have unique names when compiled..." could be confusing: even before this PR, within stand-alone MPAS-A, the name "cloud_diagnostics" is unique, for example.

2022-10-18 18:14 UTC, gdicker1 commented
@mgduda let me know what you think!

2022-10-19 16:33 UTC, mgduda commented
> @mgduda I edited the PR description, let me know what you think!

The new PR description looks good -- thanks! I had just one other comment on the README.

2022-10-20 23:15 UTC, mgduda requested changes

2022-10-25 17:16 UTC, gdicker1 commented on src/core_atmosphere/diagnostics/README
> +   with "mpas_" to prevent name conflicts.
We did. Does the force push to bcfa498 solve this for you?

(I force pushed to split a commit that both updated the README and a module name)

2022-10-26 18:41 UTC, mgduda commented on src/core_atmosphere/diagnostics/README
> +   with "mpas_" to prevent name conflicts.
The `README` looks good now. Thanks!

2022-10-26 18:58 UTC, mgduda approved these changes

2022-10-26 19:00 UTC, merged